version: '3.8'
services:
  ribusdb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Letmein!
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - ribus
networks:
  ribus:
